# Generated by Django 4.2 on 2025-11-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('summary_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
